- .vscode/settings.json
- app/components/forms/index.tsx
- app/components/forms/input.tsx
- app/components/icons/IconHug.tsx
- app/components/layout/sidebar/bottom.tsx
- app/components/layout/sidebar/index.tsx
- app/components/shared/dropdown/index.tsx
- app/components/user/profile-picture.tsx
- app/database/migrations/20230223205820_add_firstname_and_lastname_make_username_unique/migration.sql
- app/database/schema.prisma
- app/entry.server.tsx
- app/modules/user/service.server.test.ts
- app/modules/user/service.server.ts
- app/modules/user/types.ts
- app/root.tsx
- app/routes/__index/index.tsx
- app/routes/items/index.tsx
- app/routes/join.tsx
- app/routes/oauth.callback.tsx
- app/routes/user.tsx
- app/styles/global.css
- app/utils/index.ts
- app/utils/user.ts
- cypress/support/delete-user.ts
- mocks/handlers.js
- mocks/index.js
Adding some basic fields to the user model:
- username
- firstName
- lastName
Also, adding the tests and updating user edit form.
> User model adjustments

- app/atoms/notifications.ts
- app/components/category/category-select.tsx
- app/components/items/form.tsx
- app/components/markdown/markdown-editor.tsx
- app/components/shared/toast.tsx
- app/modules/item/service.server.ts
- app/routes/_layout+/_layout.tsx
- app/routes/_layout+/items.$itemId.tsx
- app/routes/_layout+/items.$itemId_.edit.tsx
- app/routes/_layout+/items.new.tsx
- package-lock.json
- package.json
Editing item view is already done so I am merging this. Already started to work on toast here but will finish it in another branch.
> 80 edit item

- app/components/items/delete-item.tsx
- app/components/items/notes/new.tsx
- app/components/items/notes/notes.tsx
- app/components/layout/header/index.tsx
- app/components/shared/button.tsx
- app/components/shared/sub-heading.tsx
- app/components/shared/textual-divider.tsx
- app/routes/_layout+/items.$itemId.tsx
Hi @DonKoko, Item page is now developed responsive for all screens as discussed in issue #94. 
Please review it. Thanks
> 94 develop item page mobile responsive

- app/components/forms/input.tsx
- app/components/list/filters/category-checkbox-dropdown.tsx
- app/components/list/filters/filters.tsx
- app/components/list/filters/search-form.tsx
- app/components/list/list-item.tsx
- app/components/list/list.tsx
- app/routes/_layout+/items._index.tsx
Hi @DonKoko, 
The item index page is developed for all screens as discussed in issue #96 
Please review it.
Thanks.
> developed items index page mobile responsive

- app/components/layout/header/index.tsx
- app/routes/_layout+/assets._index.tsx
- app/styles/global.css
As discussed in the issue #182
the table cells of assets index page are improved on small screens (mobile)
> Improvement in table cells of assets index page on small screens

- app/components/assets/actions-dropdown.tsx
- app/components/assets/delete-asset.tsx
- app/components/custody/custodian-select.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/styles/asset.css
- app/styles/layout/custom-modal.css
/claim #296 
1. Active dropdown when scan qr, only on mobile screen. 
2. Follow the design guide provided.
> Issue 296 active dropdown when scan qr

- app/components/forms/password-input.tsx
Fix the position of error when error occurs.
> fix position of icon

- .github/workflows/deploy.yml
- .github/workflows/test.yml
Refactor- 
- Deploy workflow will only run on `push` trigger (along with tests).
- Passed secrets to tests called by Deploy.
- Remove duplicate tests from Deploy.
- Remove undeclared environment.
> Improvements in workflow

- .gitignore
- app/database/migrations/20230909001745_add_view/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
closes #314 
use full text search to search asset by title, description, tag.name, location.name, category.name
> use full text search for asset searching

- app/components/category/category-select.tsx
- app/components/shared/tag.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/locations.$locationId.tsx
> ui updates in badges, assets-index page and other components

- app/components/assets/custom-fields-inputs.tsx
- app/components/custom-fields/form.tsx
- app/components/shared/button.tsx
- app/routes/_layout+/settings.custom-fields.index.tsx
- app/utils/custom-fields.ts
> fix: zod date type required for custom fields; UI styling fixes

- .husky/pre-commit
- app/database/migrations/20231002153143_org_id_assets/migration.sql
- app/modules/asset/service.server.ts
- app/modules/asset/types.ts
- app/modules/category/service.server.ts
- app/modules/custom-field/service.server.ts
- app/modules/location/service.server.ts
- app/modules/tag/service.server.ts
- app/modules/team-member/service.server.ts
- app/routes/_layout+/assets.$assetId.duplicate.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/assets.export.$fileName[.csv].tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/_layout+/locations.$locationId.add-assets.tsx
- app/routes/qr+/$qrId_.contact-owner.tsx
- app/utils/import.server.ts
- package.json
> Add Org support to Asset CRUD

- app/routes/_layout+/settings.subscription.tsx
- app/routes/_layout+/settings.workspace.tsx
> added breadcrumb in settings child routes

- app/components/location/location-select.tsx
- app/modules/asset/service.server.ts
> enabled clearing location on edit page

- app/database/migrations/20231006131408_org_id_custom_field/migration.sql
- app/database/schema.prisma
- app/routes/_layout+/settings.custom-fields.$fieldId_.edit.tsx
- app/routes/_layout+/settings.custom-fields.index.tsx
- app/routes/_layout+/settings.custom-fields.new.tsx
> make org mandatory for customFields

- docs/asset-search.md
- docs/get-started.md
> fix: typos

- app/components/assets/custom-fields-inputs.tsx
- app/components/location/location-select.tsx
- app/routes/_layout+/settings.workspace.tsx
- Made workspace page mobile responsive
- Fixed z-index issue of custom field datepicker
- Fixed location select conflicting click event issue
> fixed mobile UI bugs

- app/database/migrations/20231009125120_org_id_qr/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
- app/modules/qr/service.server.ts
- app/modules/qr/utils.server.ts
- app/modules/user/service.server.ts
- app/routes/_layout+/admin-dashboard.$userId.tsx
- app/routes/_layout+/assets.$assetId.qr.tsx
- app/routes/qr+/$qrId.tsx
> add orgID to QR codes

- app/modules/tag/service.server.ts
- package-lock.json
- package.json
> chore: upgrade prisma to 5X

- app/components/scan-qr/qrcode-scanner.tsx
> removed asset scanned message

- app/components/workspace/delete-member.tsx
- app/components/workspace/nrm-actions-dropdown.tsx
- app/routes/_layout+/settings.team.tsx
> fix queries to deleting teamMembers works peroperly

- app/modules/asset/service.server.ts
> fix: trim search term and make multiple spaces into 1

- app/database/migrations/20231118003409_bookings/migration.sql
- app/database/migrations/20231120193948_booking_custodian/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
- app/modules/booking/index.ts
- app/modules/booking/service.server.ts
> [wip] bookings

- app/database/migrations/20231121144115_making_name_of_category_unique_within_organization/migration.sql
- app/database/migrations/20231121173002_make_name_unique_for_tag_asset_loc_custom/migration.sql
- app/database/schema.prisma
> migration: migrate duplicate entity names and make entity name unique inside org

- app/database/migrations/20231122141222_deduplicate_team_member/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
- app/modules/team-member/service.server.ts
- app/modules/user/service.server.ts
- app/routes/_layout+/assets.$assetId.give-custody.tsx
- app/routes/_layout+/settings.team.add-member.tsx
- app/routes/_layout+/settings.team.tsx
- app/utils/dashboard.server.ts
> migrate(teamMember): migrate organization foriegn key; deduplicate name

- app/components/assets/form.tsx
- app/components/assets/import-content.tsx
- app/components/custom-fields/form.tsx
- app/components/location/form.tsx
- app/database/migrations/20231121144115_making_name_of_category_unique_within_organization/migration.sql
- app/database/migrations/20231121173002_make_name_unique_for_tag_asset_loc_custom/migration.sql
- app/database/migrations/20231122141222_fix_team_member_organization_relation/migration.sql
- app/database/migrations/20231123131058_add_unique_constraint_to_team_member_name/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
- app/modules/category/service.server.ts
- app/modules/custom-field/service.server.ts
- app/modules/location/service.server.ts
- app/modules/tag/service.server.ts
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets.import.tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/_layout+/categories.$categoryId_.edit.tsx
- app/routes/_layout+/categories.new.tsx
- app/routes/_layout+/locations.$locationId_.edit.tsx
- app/routes/_layout+/locations.new.tsx
- app/routes/_layout+/settings.custom-fields.$fieldId_.edit.tsx
- app/routes/_layout+/settings.custom-fields.new.tsx
- app/routes/_layout+/settings.team.add-member.tsx
- app/routes/_layout+/tags.$tagId_.edit.tsx
- app/routes/_layout+/tags.new.tsx
- app/routes/api+/asset.refresh-main-image.ts
- app/utils/error.ts
Code that needs refactoring due to changes in DB structure:
Asset:
- ~[x] Create~
- ~[x] Update~
Tag:
Category:
Location:
Custom Field
Team Member:
- ~[x] Create~
- ~[x] Update~
EDIT: We have changed our mind and decided we will drop the unique name for asset and team member
> 567 bug non unique names on models are causing issues

- app/components/booking/form.tsx
- app/routes/_layout+/bookings._index.tsx
added search on bookings index and few UI fixes
> bookings frontend

- app/components/custom-fields/form.tsx
- app/hooks/use-formbricks.ts
- app/modules/custom-field/service.server.ts
- app/modules/tier/service.server.ts
- app/routes/_layout+/_layout.tsx
- app/routes/_layout+/settings.custom-fields.$fieldId_.edit.tsx
- app/routes/_layout+/settings.custom-fields.index.tsx
- app/routes/_layout+/settings.custom-fields.new.tsx
- package.json
There was an issue with how limits are handled for custom fields. It was counting everything instead of just active ones.
> fix:custom fields limit

- app/database/migrations/20231213225815_add_self_service_org_role/migration.sql
- app/database/schema.prisma
- app/modules/organization/context.server.ts
- app/modules/organization/service.server.ts
- app/routes/_layout+/assets.$assetId.duplicate.tsx
- app/routes/_layout+/assets.$assetId.give-custody.tsx
- app/routes/_layout+/assets.$assetId.note.tsx
- app/routes/_layout+/assets.$assetId.qr.tsx
- app/routes/_layout+/assets.$assetId.release-custody.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets.$assetId.update-location.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/assets.export.$fileName[.csv].tsx
- app/routes/_layout+/assets.import.tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/_layout+/assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/qr+/$qrId.tsx
- app/utils/permissions/index.ts
- app/utils/permissions/permission.validator.server.ts
- app/utils/permissions/types.ts
- app/utils/roles.server.ts
> feat: add more granular roles and permissions

- app/components/custody/custodian-select.tsx
- app/components/location/location-select.tsx
- package-lock.json
> fixed select-input's option selection issue

- app/components/booking/booking-assets-column.tsx
- app/database/migrations/20231215142649_add_checkout_status_2_asset/migration.sql
- app/database/schema.prisma
- app/entry.server.tsx
- app/modules/asset/service.server.ts
- app/modules/booking/constants.ts
- app/modules/booking/service.server.ts
- app/modules/booking/types.ts
- app/modules/booking/worker.server.ts
- app/utils/list.ts
- app/utils/scheduler.server.ts
- fix(bookings): show assets from current booking in the asset select dialog
- feat(bookings): update asset status on booking status change
- feat(bookings): use scheduler to auto update booking status to overdue
> booking backend changes

- .gitignore
- .husky/pre-commit
- app/modules/asset/service.server.ts
- app/modules/booking/email-helpers.ts
- app/modules/booking/service.server.ts
- app/modules/booking/types.ts
- app/modules/booking/worker.server.ts
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.new.tsx
- app/utils/client-hints.tsx
- package.json
- fix(bookings): use localised date in booking emails
- fix(assets): return available to book assets only when booking search is made
- fix(bookings): send checkin reminder immediately if checkin reminder deadline has passed already
-   fix(bookings): update asset status for assets added after booking started
> backend fixes to bookings

- app/components/assets/form.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/settings.team.add-member.tsx
> fix: trimming whitespaces on asset title and team member name before saving

- app/components/layout/header/index.tsx
- app/routes/_layout+/settings.custom-fields.$fieldId_.edit.tsx
- app/routes/_layout+/settings.custom-fields.new.tsx
- app/routes/_layout+/settings.tsx
- app/routes/_layout+/settings.workspace.$workspaceId.edit.tsx
- app/routes/_layout+/settings.workspace.new.tsx
> fixed broken UI on custom fields pages

- app/emails/invite-template.tsx
- app/modules/booking/service.server.ts
- app/modules/invite/helpers.ts
- app/routes/_layout+/bookings._index.tsx
- app/routes/_layout+/settings.team.invite-user.tsx
- app/routes/_layout+/settings.team.tsx
Some small text fixes and UI tweaks.
> Bookings fixes

- fly.toml
Increasing the limit of the max connections on fly.io
> fix: increasing limit of connections

- app/components/icons/library.tsx
- app/components/list/pagination/pagination.tsx
> UI: go to first/last page buttons in pagination

- Dockerfile
- package-lock.json
There were some issues with the app building and with prisma that appeared on node-18 so we are updating to node@lts. At the moment of releasing this LTS = v20.11.0
> updating to node@lts

- app/components/assets/actions-dropdown.tsx
- app/components/assets/export-button.tsx
- app/components/assets/import-button.tsx
- app/components/booking/actions-dropdown.tsx
- app/components/booking/form.tsx
- app/components/dashboard/checklist.tsx
- app/components/layout/header/index.tsx
- app/components/layout/sidebar/bottom.tsx
- app/components/layout/sidebar/overlay.tsx
- app/components/layout/sidebar/sidebar.tsx
- app/components/list/content-wrapper.tsx
- app/components/list/filters/filters.tsx
- app/components/list/list-header.tsx
- app/components/location/actions-dropdown.tsx
- app/components/shared/controlled-action-button.tsx
- app/components/table/table.tsx
- app/routes/_layout+/_layout.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/bookings.tsx
- app/routes/_layout+/categories.tsx
- app/routes/_layout+/locations._index.tsx
- app/routes/_layout+/tags.tsx
- app/styles/global.css
resolves UI feedback mentioned in #681
> UI updates

- app/entry.server.tsx
- app/modules/booking/worker.server.ts
- app/routes/_layout+/_layout.tsx
- app/routes/healthcheck.tsx
- app/utils/scheduler.server.ts
Changing how we register workers and initialize pg-boss. Also a tiny optimization on healthcheck endpoint.
> Fix: initialization of pgboss

- app/modules/asset/service.server.ts
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/locations.$locationId.add-assets.tsx
- added option to get paginated assets either via the AssetSearchView or directly from assets. This is in order to get small performance improvements in certain views
> improving asset search performance

- app/modules/booking/service.server.ts
- we had a case where removing a asset with status CHECKED_OUT from any booking, would reset its status back to AVAILABLE: https://github.com/Shelf-nu/shelf.nu/issues/703#issuecomment-1944315975. This has been fixed by implementing an extra check
> fixing asset status bug

- app/components/errors/index.tsx
- app/emails/bookings-updates-template.tsx
- app/emails/components/footers.tsx
- app/modules/booking/email-helpers.ts
- app/modules/booking/service.server.ts
- app/modules/organization/service.server.ts
- app/routes/_auth+/join.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/utils/list.ts
- sending separate emails to all admins if a booking has been made by self service user
- Made dynamic footers of emails based on weather its for admin or normal user
- Changed subject of reservation email to make it more clear
- Fixed a password-is-too short error. Error was just palceholder
- When searching and status was set to all, we didnt handle the case so it was breaking as ALL is not a real status
> Bookings bugs fixes

- app/emails/transporter.server.ts
- app/utils/mail.server.ts
- We were creating a new nodemailer.Transporter on every invocation of sendEmail.
- We now just create a singleton in transporter.server.ts
> nodemailer transporter singleton

- app/modules/asset/service.server.ts
- app/modules/booking/email-helpers.ts
- app/modules/booking/service.server.ts
- app/modules/user/service.server.ts
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- Created a createNotes function that can create the same note for multiple assets
- Removed await from createNotes as we expect it will not fail and we shouldnt block the thread to wait for it
- adding try/catch on getUser function
- added notes for deleting a booking
- added notes for cancelling a booking
- added notes for checking out a booking
- added notes for checking in a booking
> Bookings notes

- app/components/marketing/crisp.tsx
- added email when intiating crisp
- Added name of the person who initiated crisp
> updated crisp

- app/components/assets/import-content.tsx
- app/components/custody/custodian-select.tsx
- app/styles/global.css
> fixed import assets success message issue and custodian select ui

- app/components/list/pagination/pagination.tsx
- app/hooks/index.ts
- app/hooks/use-pagination.ts
- app/modules/asset/service.server.ts
- app/modules/team-member/service.server.ts
- app/modules/user/service.server.ts
- app/routes/_layout+/admin-dashboard+/users.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.tsx
- app/routes/_layout+/categories.tsx
- app/routes/_layout+/locations.$locationId.add-assets.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/locations._index.tsx
- app/routes/_layout+/settings.custom-fields.index.tsx
- app/routes/_layout+/tags.tsx
- app/utils/list.ts
- Created a hook that returns all data + function needed for pagination
- Pagination links are no longer coming from the server, but rather completly handled by params
> Reworked pagination

- app/modules/user/service.server.ts
- app/routes/_auth+/_auth.tsx
- app/routes/_auth+/accept-invite.$inviteId.tsx
- app/routes/_auth+/forgot-password.tsx
- app/routes/_auth+/login.tsx
- app/routes/_auth+/oauth.callback.tsx
- app/routes/_auth+/reset-password.tsx
- app/routes/_auth+/verify-email.tsx
fixing issues with auth caused by change of how sessions are handled
> fix: Auth fixes

- app/components/category/category-select.tsx
- app/modules/organization/service.server.ts
- app/routes/_auth+/login.tsx
- app/routes/_layout+/settings.workspace.index.tsx
- Made category-select scrollable
- fixed issue with workspaces you dont own not showing in settings/workspace
- added a try/catch to some organization function for better error handling and overview
Closes #788
> fixed a few small bugs

- app/routes/healthcheck.tsx
- fly.toml
- package.json
There was an issue with our start command. It was using `remix-serve` instead of node. I am not even sure how it worked.
> Hono deploy fix

- app/components/dynamic-dropdown/dynamic-dropdown.tsx
- app/components/dynamic-dropdown/empty-state.tsx
- app/components/dynamic-select/dynamic-select.tsx
- app/components/icons/library.tsx
- Made sure the show all button only shows when we are not searching
- Added an empty state design
> polishing dynamic dropdown and select

- app/routes/_layout+/bookings.new.tsx
It was just some bad code that didn't consider that the current user might not be the owner.
Has been adjusted and fixed
> making sure the correct user is added as the owner of the org

- app/routes/_auth+/accept-invite.$inviteId.tsx
Microsoft's "Safe links" create an issue with the token in the url search params. We decode the url before getting the params to ensure that everything is right.
> decoding url before consuming token

- app/components/booking/form.tsx
- app/components/custody/custodian-user-select.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- There was an issue with how the owner of the org was added to the teamMembers
- This has been solved and adjusted to work in the same way as on booking.new
- A new custodianSelect component is created, that is to be user only for bookings, where only users can be given custody
- improved the querying of the data on bookingId to improve performance
> fixing custodian select on booking page

- app/components/layout/breadcrumbs/breadcrumb.tsx
- app/emails/bookings-updates-template.tsx
- app/modules/asset/service.server.ts
- app/modules/booking/service.server.ts
- app/modules/category/service.server.ts
- app/modules/organization/service.server.ts
- app/modules/tag/service.server.ts
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/categories.$categoryId_.edit.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/settings.workspace.$workspaceId.edit.tsx
- app/routes/_layout+/tags.$tagId_.edit.tsx
- Clicking a link to a booking, will now set the correct orgId if present in URL and allowed
- breadcrumbs for bookings should show now
- updated some helper functions of tags, categories and workspace to scope based on orgId
> fixing some bugs related to org and other modules

- app/routes/api+/asset.refresh-main-image.ts
- app/utils/storage.server.ts
- fixing timing of signed token
- fixing how we parse filename in the route
> implementing fixes to image refresh

- app/routes/api+/model-filters.ts
> remove limit from search query result in model-filters

- app/routes/_layout+/admin-dashboard+/$userId.tsx
- organizations listed per user were not correct. Was listing the current user organizations rather than the one we are viewing
- changed the functionality to not only list organizations that the user owns, but also ones that they belong
- added a column showing which orgs are owned by that user
> fixes to admin dashboard

- app/components/assets/actions-dropdown.tsx
- app/components/layout/header/index.tsx
- app/components/tag/tags-autocomplete.tsx
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/locations.$locationId.add-assets.tsx
- Added tags to asset form dont clear on view revalidation
- fixed headers in add-assets modals for booking and location
- completely fixed add-assets modals' design to be consistent and cleaner
- fixed button inside button on asset actions-dropdown
> implementing more fixes

- app/components/custody/custodian-user-select.tsx
- app/modules/tier/service.server.ts
- server/index.ts
- Don't capture error for no more custom fields allowed
- Fix placeholder on custodian user select
> small fixes

- app/components/assets/form.tsx
- app/components/dynamic-dropdown/dynamic-dropdown.tsx
- app/components/dynamic-select/dynamic-select.tsx
- app/components/layout/dialog.tsx
- app/utils/model-filters.ts
closes #903 and implements new style of `DynamicSelect` on mobile
> Updating dynamic select and dropdown

- app/routes/_auth+/join.tsx
- app/routes/_layout+/assets.$assetId.tsx
- Improving email validation
- Improving error message for using invalid email
> Register form improvement

- app/components/booking/availability-select.tsx
- app/components/custody/custodian-user-select.tsx
- app/components/forms/select.tsx
- app/components/layout/sidebar/organization-select.tsx
- app/utils/use-controlled-dropdown-menu.ts
- when clicking anywhere outside the dropdown it closes, however this creates an issue when one of the actions in a dropdown opens an alertdialog for confirmation. Clicking wont work because the dialog gets closed before the button click happens. This fix solves this. closes https://github.com/Shelf-nu/shelf.nu/issues/956
- [fixing issue with click through on Select via the core component](https://github.com/Shelf-nu/shelf.nu/commit/5e347d82416a7dcbd43207f349b2a612115113db) - this is a known radix issue
> Fix small ux bugs

- app/modules/booking/service.server.ts
- app/modules/booking/types.ts
- app/routes/_layout+/bookings.$bookingId.tsx
Because of changes we did on how this view works, we had to do some refactoring to make sure that data from the form on the left side is saved in all cases when the booking is being updated. Now all 4 cases will always save the data:
- save
- reserve
- check out
- check in
Closes #962
> refactoring the .bookingId action to now also save the data on reserve

- app/components/assets/form.tsx
- app/components/dynamic-select/dynamic-select.tsx
- app/components/location/location-select.tsx
- app/routes/_layout+/assets.$assetId.give-custody.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
> fix(dynamic-select-clear): add allowClear prop to dynamic-select

- app/modules/auth/components/continue-with-email-form.tsx
Fixes #994 
I have updated the text in button when using the login/signup using the OTP
when doing signup 
when doing login
> fix [Feature request]: Language change #994

- app/components/layout/sidebar/bottom.tsx
- app/components/layout/sidebar/chat-with-an-expert.tsx
- app/components/layout/sidebar/sidebar.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/styles/layout/calendar.css
- Updating a booking was not passing the hints to the newBookingFormSchema so it was not validating the date/time correctly
- Fixing user dropdown overflow of email
- Fixing user dropdown menu buttons sizing
- Making the supportBanner close with optimistic ui
- Fixing some stylings in calendar: focus & selected state for events + min height of dates
> fixing booking date validation + some small improvements:

- app/components/assets/custom-fields-inputs.tsx
- app/components/forms/form-row.tsx
- app/modules/asset/service.server.ts
- app/utils/custom-fields.ts
> Allow user to clear date field value

- app/hooks/use-main-menu-items.tsx
- app/routes/_layout+/account-details.subscription.tsx
- app/routes/_layout+/settings.custom-fields.$fieldId_.edit.tsx
- fixing which menu items are displayed
- removing permission requirement on subscription action
- Dont capture custom fields limit error
> fix: further fixes related to new settings structure and self service users

- app/routes/_layout+/bookings.new.tsx
> Fix : As a Self-service user the Custodian field appear empty in the initial modal when creating a booking

- app/modules/asset/service.server.ts
- app/routes/_layout+/assets.$assetId.tsx
making sure all images were deleted before asset deletion
> Fix 884 asset duplicate image deletion

- app/components/assets/asset-custody-card.tsx
- app/modules/asset/fields.ts
- app/modules/asset/service.server.ts
- app/routes/_layout+/assets.$assetId.overview.tsx
- app/routes/_layout+/assets.$assetId.tsx
> showing booking on asset page

- app/routes/_layout+/assets.$assetId.overview.tsx
- app/routes/_layout+/assets._index.tsx
> fix custodian image not showing asset page

- app/components/forms/select.tsx
- app/components/list/filters/sort-by.tsx
- app/modules/asset/service.server.ts
- app/routes/_layout+/assets._index.tsx
- app/utils/list.ts
Added list sorting to asset index. Lets test it and if its good, we can implement it on other pages as well.
> Sort lists

- app/modules/asset/service.server.ts
- app/routes/_layout+/assets.$assetId.overview.duplicate.tsx
- app/utils/custom-fields.ts
/claim #986
/fixes #986 
Handling the custom fields creation for duplicate assets
> Bug 986 duplicate asset custom fields creation

- app/modules/booking/pdf-helpers.ts
- app/routes/_layout+/bookings.$bookingId.generate-pdf.$fileName[.pdf].tsx
booking period with timezone handled
> fix:handle timezone issue in pdf booking period

- app/routes/_layout+/kits.$kitId.manage-assets.tsx
- app/routes/_layout+/kits.$kitId.tsx
- docs/sso/providers/google-workspace.md
- removed reserved from statuses on action validation
- added client side control to make sure that manage assets button is disabled
> Fixing issue with adding assets to a kit that is part of booking

- app/components/assets/import-content.tsx
- app/modules/asset/service.server.ts
- app/modules/category/service.server.ts
- app/modules/custom-field/service.server.ts
- app/modules/location/service.server.ts
- app/modules/tag/service.server.ts
- app/modules/team-member/service.server.ts
Fixes #1072
Importing still have lots of potential for improvement. This PR just improves how error messages are displayed.
> improving import error messages

- app/components/location/scan-details.tsx
- app/routes/_layout+/assets.$assetId.overview.tsx
- app/routes/qr+/$qrId.tsx
> fix: make sure qr scan redirects to correct url to be able to update position using usePosition hook

- app/components/assets/form.tsx
- app/components/booking/form.tsx
- app/components/dynamic-select/dynamic-select.tsx
- app/components/forms/categories-input.tsx
- app/components/forms/inner-label.tsx
- app/components/forms/input.tsx
- app/components/kits/form.tsx
- app/components/location/form.tsx
- app/components/location/location-select.tsx
- app/components/marketing/crisp.tsx
- app/components/shared/controlled-action-button.tsx
- app/components/workspace/edit-form.tsx
- app/components/workspace/form.tsx
- app/routes/_layout+/assets.$assetId._index.tsx
- app/routes/_layout+/assets.$assetId.overview.check-out.tsx
- app/routes/_layout+/kits.$kitId.check-out.tsx
- app/styles/global.css
- fixing responsiveness of input fields
- fixing how dynamic select renders label
- fixing responsiveness of assets form
- updating every place `dynamicSelect` is used to reflect the new API of the component
- Created a component for `InnerLabel` to be used in Input component and `DynamicDropdown`
- Updated all forms to use the new API that works with `InnerLabel`
- Updated some labels that had spelling mistakes
- Fixes some styles to make them more generic related to `InnerLabel`
- fix bug with reserve button, showing a wrong tooltip, while page is submitting
- fix bug with check-out button showing wrong tooltip, while page is submitting
- adding proper label to currency field in workspace
- adding subtitle to currency field, explaining how to use it and to contact support if currency is …
> fix: general issues from #957

- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.new.tsx
- remove old code from booking.new that is not needed anymore
- remove old code from booking._edit that is not needed anymore
- slight code optimization due to the changes
> fix: owner showing 2 times in booking custodian select:

- app/modules/asset/service.server.ts
- app/modules/location/service.server.ts
- app/modules/tag/service.server.ts
- fixing issue when no tags column is present
- fixing issue when no locations column is present
- removing batched create as it was giving issues
> fix: fixing some import issues:

- .env.example
- app/config/shelf.config.ts
- app/config/types.ts
- app/modules/auth/service.server.ts
- app/routes/_auth+/join.tsx
- app/routes/_auth+/login.tsx
- app/routes/_auth+/oauth.callback.tsx
- app/routes/_auth+/sso-login.tsx
- app/utils/env.ts
- [disabled signup functionality](https://github.com/Shelf-nu/shelf.nu/pull/1123/commits/55ed2e98fceb1a5e4e750851c0a9da1885bc3a27)
- [adding config option to disable SSO](https://github.com/Shelf-nu/shelf.nu/pull/1123/commits/d8886648d18a340d3cdf81f6817207676cab27fc)
- [making sure the disableSSO and disableSignup errors are not captured …](https://github.com/Shelf-nu/shelf.nu/pull/1123/commits/926e418fd8a3c03676eca916959d51a03c735afc)
> feat: allow to disable auth features

- app/components/location/scan-details.tsx
- app/modules/scan/service.server.ts
- app/modules/scan/utils.server.ts
> feat:add scaaned by details

- app/components/tag/bulk-actions-dropdown.tsx
- app/components/tag/bulk-delete-dialog.tsx
- app/modules/tag/service.server.ts
- app/routes/_layout+/tags.tsx
- app/routes/api+/tags.bulk-actions.ts
> feat(tags-bulk-actions): format files

- app/components/list/index.tsx
- app/components/location/bulk-actions-dropdown.tsx
- app/components/location/bulk-delete-dialog.tsx
- app/components/shared/button.tsx
- app/modules/location/service.server.ts
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/categories.tsx
- app/routes/_layout+/kits._index.tsx
- app/routes/_layout+/locations._index.tsx
- app/routes/_layout+/tags.tsx
- app/routes/api+/locations.bulk-actions.ts
- app/styles/global.css
> feat(location-bulk-actions): create bulk delete locations feature

- app/components/assets/import-content.tsx
- app/modules/asset/service.server.ts
- app/modules/asset/types.ts
- app/modules/kit/service.server.ts
- app/utils/csv.server.ts
- app/utils/custom-fields.ts
- app/utils/subscription.server.ts
- public/static/shelf.nu-example-asset-import-from-content.csv
- change delimiter to comma
- update docs
- updated how detailed errors are presented to users
- updated template
[import kit:](https://github.com/Shelf-nu/shelf.nu/pull/1128/commits/358e796ec02c2aa7e60dc615da358345b1816186)
- allow for adding a kit when importing
- update import documentation
- update template file
- update related types
> improvement: update csv imports

- app/components/assets/actions-dropdown.tsx
- app/components/booking/delete-booking.tsx
- app/components/booking/generate-booking-pdf.tsx
- app/components/booking/kit-row-actions-dropdown.tsx
- app/components/booking/remove-asset-from-booking.tsx
- app/components/bulk-update-dialog/bulk-update-dialog.tsx
- app/components/kits/actions-dropdown.tsx
- app/components/kits/delete-kit.tsx
- app/components/kits/remove-asset-from-kit.tsx
- app/components/layout/sidebar/organization-select-form.tsx
- app/components/layout/sidebar/organization-select.tsx
- app/components/list/pagination/index.tsx
- app/components/location/delete-location.tsx
- app/components/shared/button.tsx
- app/components/shared/dropdown.tsx
- app/components/workspace/nrm-actions-dropdown.tsx
- app/routes/_layout+/settings.team.tsx
- Change how disabled state of buttons is styled
- fix a small copy mistake in team page
> Fix: small updates

- app/components/list/index.tsx
- app/components/nrm/bulk-actions-dropdown.tsx
- app/components/nrm/bulk-delete-dialog.tsx
- app/modules/team-member/service.server.ts
- app/routes/_layout+/settings.team.nrm.tsx
- app/routes/_layout+/settings.team.users.tsx
- app/routes/api+/nrm.bulk-actions.ts
> feat(nrm-bulk-actions): create feature to bulk delete team members

- app/components/layout/horizontal-tabs/index.tsx
- app/components/layout/horizontal-tabs/types.ts
- app/components/shared/date.tsx
- app/root.tsx
- app/routes/_layout+/admin-dashboard+/$userId.tsx
- app/routes/_layout+/admin-dashboard+/_layout.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.assets.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.members.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.qr-codes.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.tsx
- app/routes/_layout+/admin-dashboard+/users.tsx
- app/routes/_layout+/assets._index.tsx
See members for org + assets. Closes #1139
> feature:  request see all team members or link to them from admin dashboard

- app/atoms/bulk-update-dialog.ts
- app/components/booking/bulk-actions-dropdown.tsx
- app/components/booking/bulk-archive-dialog.tsx
- app/components/booking/bulk-cancel-dialog.tsx
- app/components/booking/bulk-delete-dialog.tsx
- app/components/bulk-update-dialog/bulk-update-dialog.tsx
- app/components/dashboard/assets-for-each-month.tsx
- app/components/dashboard/most-scanned-categories.tsx
- app/components/shared/icons-map.tsx
- app/components/table.tsx
- app/modules/booking/service.server.ts
- app/modules/booking/utils.server.ts
- app/routes/_layout+/bookings.tsx
- app/routes/api+/bookings.bulk-actions.ts
> feat(booking): Booking bulk actions

- app/utils/csv.server.ts
using the export function when there are no assets, didn't give a proper error message so it was confusing for the user
> fix: export function error handling

- app/components/errors/index.tsx
- app/modules/invite/service.server.ts
- app/routes/_layout+/settings.team.users.invite-user.tsx
- app/utils/error.ts
- package-lock.json
- package.json
- made so error message allows new lines via `\n`
- removed cuid2 package
- changed traceId generation to uuid4 to fit requirements of sentry
- generate traceId using crypto.randomUUID() which is available both on client and nodejs
- made way more detailed and explicit error messages for accepting invites
> fix: error handling on invite accept

- app/components/assets/custom-fields-inputs.tsx
- app/components/assets/import-content.tsx
- app/modules/custom-field/service.server.ts
- options custom field value wont render Select.Item for items where value is an empty string
- prevent import of custom fields from creating empty options
> fix: issues with options custom field empty values

- app/atoms/list.ts
- app/components/assets/bulk-actions-dropdown.tsx
- app/components/assets/bulk-delete-dialog.tsx
- app/components/booking/bulk-actions-dropdown.tsx
- app/components/booking/bulk-archive-dialog.tsx
- app/components/booking/bulk-cancel-dialog.tsx
- app/components/booking/bulk-delete-dialog.tsx
- app/components/bulk-update-dialog/bulk-update-dialog.tsx
- app/components/category/bulk-delete-dialog.tsx
- app/components/custom-fields/bulk-actions-dropdown.tsx
- app/components/custom-fields/bulk-activate-dialog.tsx
- app/components/custom-fields/bulk-deactivate-dialog.tsx
- app/components/kits/bulk-actions-dropdown.tsx
- app/components/kits/bulk-delete-dialog.tsx
- app/components/list/bulk-actions/bulk-list-header.tsx
- app/components/list/bulk-actions/bulk-list-item-checkbox.tsx
- app/components/list/index.tsx
- app/components/location/bulk-delete-dialog.tsx
- app/components/nrm/bulk-actions-dropdown.tsx
- app/components/nrm/bulk-delete-dialog.tsx
- app/components/tag/bulk-delete-dialog.tsx
- app/utils/list.ts
> Change selection of id to whole item object in bulk items

- app/components/zxing-scanner.tsx
> fix(scan): stop scan while redirection

- app/routes/_auth+/reset-password.tsx
/claim #1160 
add search params
> chore:add search params on successful reset password

- app/modules/booking/pdf-helpers.ts
- app/routes/_layout+/bookings.$bookingId.generate-pdf.$fileName[.pdf].tsx
/claim #1162 
add ki column to the booking pdf generator
> chore: add kit column in pdf generator

- app/modules/booking/service.server.ts
- app/routes/api+/bookings.bulk-actions.ts
PR - #1120 
This PR fixes issue reported by @jurrejansen in this [comment](https://github.com/Shelf-nu/shelf.nu/issues/1120#issuecomment-2228034635)
> fix(booking): move non-db tasks outside of transaction

- app/components/list/index.tsx
> fix(bulk-action): hide bulk actions feature from self service

- app/components/forms/option-builder.tsx
- app/modules/custom-field/service.server.ts
- make sure when importing the array of options is unique
- handle error in UI when trying to add 2 options with the same name
> fix: dont allow duplicate options on custom fields

- app/components/shared/user-badge.tsx
- app/routes/_layout+/calendar.tsx
- app/styles/layout/calendar.css
- app/utils/calendar.ts
Because of adding the popover we now are fully having custom display of events so we had to re-create the original design.
> fix: styling of calendar events is broken

- docs/hooks.md
This pull request updates the documentation for the useUserRoleHelper hook. The changes include:
- removed # from useDisabled in line 138 from hooks.md
- Detailed description
- what does hook returns
- a simple conditional rendering example for usage of the hook
- dependency of the hook
> Updating hooks documentation

- Dockerfile
- app/modules/booking/pdf-helpers.ts
- docs/hooks.md
- package-lock.json
- package.json
Our PDF generator suddenly stopped working. I am not 100% sure what the reason is but I assume some of the packages and how we install chromium changed, so it was missing some libraries.
After many tests we have found a setup that works for now.
> fix: pdf generator crash

- app/modules/booking/pdf-helpers.ts
The root cause of the issue has been identified: improper handling of browser instance closures is leading to memory leaks. As the number of active instances increases, it results in excessive memory consumption and CPU usage, ultimately causing the service to become unresponsive.
what this change will do:
this fix will make sure there are no more memory leaks issues from the puppeteer.
note: only theory assumptions.
To check the theory:
run below command. if the number is huge then it is memory leak issue.(ideally restart should cleanup the existing instances, if not we need to figure out a way to kill the instances created by pupetter)
`ps aux | grep '[p]uppeteer' | wc -l
`
> fix:resolved the browser instance meory leak issue.

- app/components/booking/status-filter.tsx
- app/components/list/list-item.tsx
- app/modules/settings/service.server.ts
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/settings.team.users.$userId.$.tsx
- app/routes/_layout+/settings.team.users.$userId.assets.tsx
- app/routes/_layout+/settings.team.users.$userId.bookings.tsx
- app/routes/_layout+/settings.team.users.$userId.tsx
- app/routes/_layout+/settings.team.users.tsx
> fix: 1253 bug team archived bookings

- app/modules/report-found/service.server.ts
- app/routes/qr+/$qrId_.contact-owner.tsx
Before: Email was sent to the person who created the asset
Now: Email is sent to the owner of the organization that this asset belongs to
> adjustment: change receiver of report found email

- app/routes/_layout+/admin-dashboard+/$userId.tsx
In case a user doesn't have a customer_id, we add an action for the admin to manually create it.
> feat: allow super admin to manually create stripe customer for the users that dont have it

- app/routes/_welcome+/onboarding.tsx
Onboarding action had a few issues that were causing errors when signing up and causing the user not having a `customerId`.
- Schema validation was not done correctly for transforming string to boolean
- Password was sent with payload, even for users who already registered with password. We now remove it from the payload, just in case.
> fix: issue with onboarding schema

- app/modules/booking/service.server.ts
- app/routes/_layout+/calendar.tsx
- app/utils/calendar.ts
- allow getBookings to receive `takeAll` argument 
- Fix text overflow of multiday events
- fix z-index of popovers on calendar
> feat: allow getBookings to receive takeAll argument

- app/modules/auth/service.server.ts
- app/routes/_auth+/otp.tsx
- app/routes/_auth+/resend-otp.tsx
- Fixing which errors should be captured for OTP
- Updating the resend otp ux and code as it was buggy and not considering some cases
> fix: otp ux and resending

- app/routes/_layout+/dashboard.tsx
- app/utils/dashboard.server.ts
> Dashboard's top custodians table to include custodies via bookings

- docs/hooks.md
> updating useUserData hook from Hooks.md

- app/modules/asset/service.server.ts
> fix: transaction issue on bulk delete assets

- app/routes/_layout+/account-details.workspace.index.tsx
**Description:**
This PR solves the issue of extra $ sign showing in the popup in the workspaces tab. The issue was pretty basic, just needed to go through the codebase to find the exact codefile where this thing is mentioned, removed the $ signs from there, and that's it.
**Issue Fixed:** #1340 
**Screenshots:**
> Bug: removed the extra `$` sign appearing on the popup in workspaces tab

- app/database/migrations/20241107105011_enhance_asset_search_view_validation/migration.sql
- app/modules/asset/service.server.ts
Implementing extra validation on app level + adjusting asset search view security and validation to make sure asset is not null
> fix: Prevent no asset in in AssetSearchView

- app/components/assets/assets-index/advanced-filters/value-field.tsx
- app/components/assets/form.tsx
- app/components/dynamic-select/dynamic-select.tsx
- app/components/forms/categories-input.tsx
- app/hooks/use-model-filters.ts
- app/routes/_layout+/assets.new.tsx
- making sure that when value is disselected it gets cleraed from params
- on asset.new just in case we check for the category in the url to set the default value"
> fix: asset form category selector

- app/routes/_layout+/assets.$assetId.overview.tsx
- fix order of custom fields values on the asset page. Make them ordered based on the customField.name
> improvement: order of custom fields

- app/components/assets/asset-image.tsx
- app/components/assets/assets-index/advanced-asset-columns.tsx
- app/routes/_layout+/locations.$locationId.add-assets.tsx
- tailwind.config.ts
- added a loading state on the asset image which will show while the file is loading
- enabled image preview on advanced asset index
- small css improvement to a random bug i noticed in location.add-assets
> improvement: loading state on asset image

- app/modules/booking/types.ts
- app/modules/booking/worker.server.ts
- app/utils/scheduler.server.ts
- [adding missing attributes for production connection](https://github.com/Shelf-nu/shelf.nu/commit/17ba9e3053b3f03815b905494a7716d8dab6fa5a)
- [chore: removing legacy code that was kept only for backwards compatibility](https://github.com/Shelf-nu/shelf.nu/commit/ac09a1a255932bc79d483eecbdf9fb9ab313d5e1)
> improvement: pg boss optimizations

- app/routes/_auth+/join.tsx
- app/routes/_auth+/login.tsx
- app/routes/_auth+/send-otp.tsx
- app/utils/sso.server.ts
- create a validator function that Validates if signup is allowed for an email based on SSO configuration
- implement this function in sign up as well as otp sign up
> improvement: signup limitations

- app/components/assets/bulk-assign-tags-dialog.tsx
- app/components/assets/bulk-category-update-dialog.tsx
- app/components/assets/bulk-location-update-dialog.tsx
- app/components/location/location-select.tsx
- app/modules/asset/service.server.ts
- app/routes/api+/assets.bulk-assign-tags.ts
- app/routes/api+/model-filters.ts
- adding validations to bulk assign tags as they were missing and causing db errors
- improving UX of bulk assign category by using better wording and feedback
- fixing assign location select to work better in bulk and singular mode. Allow clear and properly set default value on singular case
- adding a type export for the model-filters loader
> improvement: fixing issues with asset bulk actions

- app/components/list/pagination/per-page-items-select.tsx
> fix: pagination issue

- app/routes/_auth+/accept-invite.$inviteId.tsx
- app/routes/_layout+/calendar.tsx
- app/styles/layout/calendar.css
- app/utils/calendar.ts
- package-lock.json
- package.json
> Improvement to Calendar View

- app/modules/team-member/service.server.ts
- app/routes/_layout+/settings.team.nrm.import-members.tsx
- package-lock.json
- update createTeamMemberIfNotExists to be case-insensitive
- update import-nrm action to use createTeamMemberIfNotExists instead of just a pure db call
> improvement: polish nrm imports

- app/routes/_auth+/reset-password.tsx
> fix: issue on reset password

- server/index.ts
> feat(auto-logout): update expiry of session to 3 days

- app/modules/asset/query.server.ts
Fix issue with case sensitive on tags filter in Advanced Index page.
> fix(tag-filter): update tag query for case insensitive

- app/components/assets/assets-index/advanced-asset-index-filters-and-sorting.tsx
- app/components/assets/assets-index/advanced-filters/helpers.ts
- app/components/assets/assets-index/advanced-filters/operator-selector.tsx
- app/components/assets/assets-index/advanced-filters/value-field.tsx
- Made the operator and value field disabled if no column is selected
- updated placeholders of all value fields if they are disabled
- fixed a bug where default(first) column would not show in the list as it would be considered selected
> fix: default state of value field in filters

- app/utils/client-hints.tsx
- app/utils/custom-fields.ts
> fix(date-custom-field): fix issue with date custom field

- app/components/layout/sidebar/sidebar.tsx
- app/components/shared/button.tsx
- app/components/shared/generic-add-to-bookings-actions-dropdown.tsx
- app/components/table.tsx
- app/hooks/use-sidebar-nav-items.tsx
- app/routes/_layout+/_layout.tsx
- update how the button component types are managed for better type safety and intellisense
- update a few ui icons
- fix gradient positioning on advanced index
> fix: Button component TS

- app/components/layout/sidebar/sidebar.tsx
- app/components/list/index.tsx
- app/components/table.tsx
- app/routes/_layout+/assets._index.tsx
> fix: scrollbar issue on assets index

- app/components/layout/sidebar/parent-nav-item.tsx
- app/components/layout/sidebar/sidebar.tsx
> fix(sidebar): fix issue with sub-menu not opening on mobile

- app/routes/api+/stripe-webhook.ts
- app/utils/env.ts
> fix(stripe-webhook): skip webhook handling for custom install of shelf

- app/components/custom-fields/form.tsx
- app/components/forms/categories-input.tsx
> fix(custom-field): fix issue with empty category in custom field

- app/components/assets/asset-image.tsx
- app/styles/global.css
> fix: image loader

- app/components/assets/assets-index/advanced-asset-columns.tsx
- app/components/assets/qr-preview-dialog.tsx
- app/components/layout/header/types.ts
- app/components/qr/qr-preview.tsx
- app/components/shared/button.tsx
- app/hooks/use-api-query.ts
- app/routes/api+/assets.$assetId.generate-qr-obj.ts
> feat(qr-id-column): create qrId column with qr preview

- app/components/booking/form.tsx
Reverts Shelf-nu/shelf.nu#1576
> Revert "feat(booking-date): update endDate when startDate is changed"

- app/modules/booking/service.server.ts
- app/modules/kit/service.server.ts
- app/modules/kit/types.ts
- app/modules/location/service.server.ts
- app/modules/team-member/service.server.ts
- app/routes/_layout+/assets.$assetId.overview.add-to-existing-booking.tsx
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.add-kits.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.new.tsx
- app/routes/_layout+/kits.$kitId.add-to-existing-booking.tsx
- app/routes/_layout+/kits.$kitId.release-custody.tsx
- app/routes/_layout+/kits.$kitId_.edit.tsx
- app/routes/_layout+/kits.new.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/locations.$locationId_.edit.tsx
- app/routes/_layout+/locations.new.tsx
- app/routes/_layout+/settings.general.tsx
- app/routes/_layout+/settings.team.nrm.$nrmId.edit.tsx
- app/routes/_layout+/settings.team.nrm.tsx
- app/routes/api+/asset.refresh-main-image.ts
- app/routes/api+/assets.add-to-booking.ts
- app/routes/api+/kit.refresh-image.ts
> Fix vulnerabilities 

- app/routes/_layout+/admin-dashboard+/$userId.tsx
- app/routes/_layout+/admin-dashboard+/users.tsx
> chore: small fixes to admin dashboard

- .gitignore
- app/components/zxing-scanner/zxing-scanner.tsx
- app/routes/_layout+/scanner.tsx
- app/styles/scanner.css
- vite.config.ts
> fix: layout issues on scanner page 

- app/components/booking/create-booking-dialog.tsx
> fix(booking-modal): update width of booking modal

- app/components/assets/asset-image.tsx
> feat(asset-image): add shortcut to close image preview

- app/routes/_auth+/forgot-password.tsx
- app/routes/_layout+/assets.$assetId.overview.add-to-existing-booking.tsx
- app/routes/api+/assets.add-to-booking.ts
- app/utils/import.server.ts
- disabled capturing of certain errors that are handled and shouldnt be showing up in sentry
> chore: capturing errors:

- app/modules/user/service.server.ts
- app/utils/roles.server.ts
- we dont throw on each group check, instead we throw if there arent any groups
> fix: how we are handling multiple sso groups

- app/utils/csv.server.ts
- Make sure only markdown fields get markdown stripped
- dont remove brackets from markdown
- update how links are changed when exporting markdown so they are visible in a clear manner
- Don't export "actions" column
> improve: asset csv export parsing:

- app/components/booking/export-bookings-button.tsx
- app/modules/booking/service.server.ts
- app/modules/booking/utils.server.ts
- app/routes/_layout+/assets.$assetId.bookings.tsx
- app/routes/_layout+/bookings.export.$fileName[.csv].tsx
- app/routes/_layout+/bookings.tsx
- app/utils/csv.server.ts
- app/utils/permissions/permission.data.ts
- app/utils/subscription.server.ts
- creating export button
- Creating route that will return csv
- sending search params from bookings index to csv export loader including handling selectAll
- created function that creates the csv for bookings
> feature: export of bookings to csv

- app/components/assets/asset-custody-card.tsx
- app/components/assets/assets-index/advanced-asset-columns.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/kits._index.tsx
- app/utils/csv.server.ts
- app/utils/user.ts
> fix(booking-export): fix issue with custodian user in export

- app/utils/csv.server.ts
> fix(booking-export): fix issue with custodian name

- app/routes/_layout+/assets.$assetId.reminders.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/reminders._index.tsx
> fix(base-reminder): fix issue with base and self user reminders

- app/components/layout/sidebar/organization-selector.tsx
> fix(organization-selector): fix scroll issue on organization selector

- app/components/booking/generate-booking-pdf.tsx
> feat(description-field): add asset description field in booking pdf

- app/components/nrm/export-nrm-button.tsx
- app/routes/_layout+/settings.team.nrm.tsx
- app/routes/api+/settings.export-nrm.$fileName[.csv].ts
- app/utils/csv.server.ts
> feat(export-nrm): create feature to export NRMs to csv

- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
> fix(booking-manage-assets): update behaviour of setting default items on manage-assets page

- app/components/booking/checkin-dialog.tsx
- app/components/booking/checkout-dialog.tsx
- app/modules/booking/helpers.ts
> refactor(early-checkin-checkout): updation functions to losee the early checking

- app/modules/asset/service.server.ts
- app/modules/booking/service.server.ts
- app/modules/custom-field/service.server.ts
- app/modules/kit/service.server.ts
- app/modules/location/service.server.ts
- make sure that if the 404 happens because the user is in the wrong org, we dont capture it
> fix: dont capture 404

- app/utils/storage.server.ts
- reverting calculateAsyncIterableSize from #1777 as its breaking the upload for some reason
> fix: error with file upload

- .env.example
- app/emails/email.worker.server.ts
- app/emails/invite-template.tsx
- app/emails/stripe/trial-ends-soon.tsx
- app/emails/stripe/welcome-to-trial.tsx
- app/modules/invite/helpers.ts
- app/routes/_auth+/accept-invite.$inviteId.tsx
- app/utils/env.ts
- package.json
> feat(replace-support-email-with-env): replace support email with env variable

- app/utils/csv.server.ts
- update labels of dates to better reflect their meaning
- add status column
> improvement: bookings csv export labels:

- app/components/booking/booking-assets-column.tsx
- app/components/booking/kit-row.tsx
- app/components/booking/list-asset-content.tsx
> fix(booking-conflicts): fix booking conflict not showing on kit

- app/modules/asset/data.server.ts
- app/modules/asset/service.server.ts
- app/modules/booking/service.server.ts
- app/routes/_layout+/bookings.tsx
- app/utils/cookies.server.ts
> feat(persist-booking-sorting): saving filters in cookie on booking index page

- CODE_OF_CONDUCT.md
- README.md
I have added a code of conduct based on the Contributor covenant: https://www.contributor-covenant.org/
> chore: adding code of conduct

- app/components/assets/assets-index/asset-index-pagination.tsx
- app/components/assets/assets-index/assets-list.tsx
Advanced index is stable nowadays, so I am removing the tag saying (Beta) and the confirmation window.
> chore: remove confirmation for switching to advanced index

- .gitignore
- app/components/booking/booking-overview-pdf.tsx
- app/modules/booking/pdf-helpers.ts
- app/utils/csv.server.ts
> fix: add tags in booking export

- app/components/list/filters/search-field-tooltip.tsx
- app/modules/asset/data.server.ts
- app/modules/asset/query.server.ts
- app/modules/asset/service.server.ts
- app/modules/types.ts
> feat(asset-search): allow asset search in qrId and customField value

- app/components/list/pagination/index.tsx
- app/components/subscription/subscriptions-overview.tsx
- app/modules/user/service.server.ts
- app/routes/_layout+/admin-dashboard+/$userId.tsx
- app/routes/_layout+/admin-dashboard+/users.tsx
adding tier filters on admin dashboard users and showing current subscription on user page for admins
> feat: admin tools

- app/components/booking/booking-statistics.tsx
- app/components/booking/page-content.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
> feat: show creator details on booking page

- app/components/assets/assets-index/advanced-asset-columns.tsx
- app/components/assets/assets-index/advanced-filters/value-field.tsx
- app/components/assets/assets-index/assets-list.tsx
- app/components/assets/form.tsx
- app/components/sequential-id-migration-modal.tsx
- app/database/migrations/20250818111026_add_sequential_id_column/migration.sql
- app/database/migrations/20250818111341_add_sequential_id_sequences/migration.sql
- app/database/migrations/20250818152417_add_flag_to_track_sequential_ids_migration/migration.sql
- app/database/schema.prisma
- app/modules/asset-index-settings/helpers.ts
- app/modules/asset/data.server.ts
- app/modules/asset/query.server.ts
- app/modules/asset/sequential-id.server.test.ts
- app/modules/asset/sequential-id.server.ts
- app/modules/asset/service.server.ts
- app/modules/asset/types.ts
- app/modules/organization/service.server.ts
- app/routes/_layout+/_layout.tsx
- app/routes/_layout+/assets.$assetId.overview.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/api+/generate-sequential-ids.tsx
- app/utils/csv.server.ts
Add comprehensive sequential ID system with organization-scoped unique identifiers
(e.g., SAM-0001, SAM-0002) for all assets, including automatic migration for
existing organizations and proper natural sorting for 100k+ assets.
- Add sequentialId field to Asset model with unique constraints
- Add hasSequentialIdsMigrated flag to Organization model
- Create PostgreSQL functions for atomic sequence management
- Add indexes for performance optimization
- Auto-generate sequential IDs for new assets with retry logic
- Bulk migration system for existing assets (180k+ tested)
- Preview next sequential ID in forms without consuming sequence
- Natural numeric sorting in asset index (handles SAM-100000 > SAM-99999)
- Search and filter support for sequential IDs
- Display sequential ID prominently …
> Feat: sequential ids

- app/components/shared/button.test.tsx
- app/modules/kit/service.server.ts
- app/routes/_layout+/assets.$assetId.note.tsx
- app/routes/_layout+/kits.$kitId.assets.assign-custody.tsx
- app/routes/_layout+/kits.$kitId.assets.manage-assets.tsx
- app/routes/_layout+/kits.$kitId.tsx
- app/routes/api+/asset.generate-thumbnail.ts
- app/routes/api+/asset.refresh-main-image.ts
Critical Security Fixes:
1. Asset Image Refresh APIs - Add organization scoping and permission validation
- /api/asset.generate-thumbnail: Add requirePermission(read) and organizationId filter
- /api/asset.refresh-main-image: Add requirePermission(read) and organizationId filter
- Prevents unauthorized access to asset images across tenant boundaries
2. Asset Note Creation - Add organization boundary validation
- /assets.$assetId/note: Validate asset belongs to user's organization before note creation
- Prevents injection of notes into other organizations' asset records
3. Kit Asset Mutations - Add organization constraints to all database operations
- /kits.$kitId.tsx: Add organizationId to kit and asset update queries
- /kits.$kitId.assets.assign-custody.tsx: Add organizationId to kit and …
> Fix multiple critical cross-tenant security vulnerabilities
