Shelf-nu/shelf.nu

- app/components/layout/sidebar/atoms.ts
- app/components/layout/sidebar/index.tsx
- app/components/layout/sidebar/menu-button.tsx
- app/components/layout/sidebar/menu-items.tsx
- app/components/layout/sidebar/overlay.tsx
- app/routes/_layout+/_layout.tsx
- app/styles/layout/sidebar.css
Hello @DonKoko,
The desktop main navigation sidebar is now responsive for all screen sizes as described in the issue #91
Please Review this. Thanks
> made main-navigation-sidebar responsive

- app/components/assets/actions-dropdown.tsx
- app/components/location/actions-dropdown.tsx
Basically when the Radix-UI dropdown is opened it adds css property "pointer-events: none" to body tag and which disables all interactions of child elements of Body tag, and the property "pointer-events: none" is removed when the user selects/clicks on the DropdownMenuItem component as it closes the dropdown menu.
previously :
Here is the previously written code , which shows that DeleteAsset component is a part of dropdown menu but is not wrapper in  DropdownMenuItem component, when Delete asset is selected it didn't removed the  "pointer-events: none"  from body as it did not closed the dropdown and we couldn't wrap the delete asset component in the DropdownMenuItem component because of conflicting events which resulted in not rendering the delete asset popup
As from the API reference …
> Solved the mentioned bug

- app/atoms/notifications.ts
- app/components/shared/toast.tsx
- app/routes/_layout+/assets.$assetId.note.tsx
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/_layout+/categories.new.tsx
- app/routes/_layout+/categories.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/locations.$locationId_.edit.tsx
- app/routes/_layout+/locations.new.tsx
- app/routes/_layout+/settings.user.tsx
- app/routes/_layout+/tags.new.tsx
- app/routes/_layout+/tags.tsx
- app/routes/api+/sse.notification.ts
- app/utils/emitter/send-notification.server.ts
fixing a bug where notifications were sent to all users instead of just the one who has to receive them.
We now send the `senderId` which is of type `User['id']` with the `sendNotification` function and then we make sure the notification is send only to users who's session `userId` matches the `senderId`
> Notifications fix

- app/routes/_auth+/forgot-password.tsx
- app/routes/_auth+/login.tsx
- app/routes/_auth+/send-magic-link.tsx
- app/utils/index.ts
- app/utils/misc.ts
Zod's `.email()` has an issue with validating email addresses where the there is a subdomain and a dash included: https://github.com/colinhacks/zod/pull/2157
So we made custom validation using `.refine()` and regex.
> replacing zod's default email validation with a custom refine function

- app/components/assets/notes/note.tsx
It was using the display date instead of `createdAt` so it was showing the wrong time.
> Fixing time ago on notes

- app/components/shared/image.tsx
- app/modules/location/service.server.ts
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/locations._index.tsx
- app/utils/date-fns.ts
#401 
- If image of location updated within 30 seconds, we add current date and time in image url.
- adding date and time in image url, browser is force to re-fetched the image
> Bugfix(401): Force to re-fetch location image, if its been updated recently

- app/styles/layout/sidebar.css
#419 
- Removed extra margin for icon and image in sidebar
- Bottom section of sidebar, making its border color transparent when sidebar is collapsed. This way menus/items in sidebar will not flicker vertically.
> Bugfix(419) - sidebar icon flicker issue

- app/components/assets/form.tsx
- app/components/category/category-select.tsx
- app/components/list/filters/category/category-checkbox-dropdown.tsx
- app/modules/asset/service.server.ts
- app/routes/_layout+/assets.$assetId.tsx
- app/routes/_layout+/assets._index.tsx
fixes #450 
- After applying Uncategorised` filter in index page
> feat: Implement "uncategorized" for assets

- app/modules/asset/service.server.ts
The if case for linking to a orphaned QR code was checking `userId` instead of `organizationId`
> fix: Fixing issue with linking QR

- app/modules/organization/service.server.ts
- app/modules/tier/service.server.ts
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/assets.export.$fileName[.csv].tsx
- app/routes/_layout+/assets.import.tsx
- app/routes/api+/admin.export-org-assets.$organizationId.$fileName[.csv].tsx
- app/utils/subscription.ts
fix: import/export permission assertions now check organization owner's `tierLimits` rather than current user. This allows all members admins of the org to do it
> fix: import/export permission assertions now check organization owner.

- app/components/assets/export-button.tsx
- app/components/shared/controlled-action-button.tsx
- app/routes/_layout+/_layout.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/assets.export.$fileName[.csv].tsx
- app/routes/_layout+/settings.general.tsx
- app/utils/subscription.ts
More clear UX about what it does. The button should not be called Export and should not be to the Import one as that creates confusion.
This button actually creates a backup of all the assets.
> improvement: moved export button

- app/components/subscription/current-plan-details.tsx
- app/components/subscription/price-cta.tsx
- app/components/subscription/prices.tsx
- app/emails/stripe/trial-ends-soon.tsx
- app/entry.server.tsx
- app/modules/booking/worker.server.ts
- app/routes/_auth+/join.tsx
- app/routes/_layout+/settings.subscription.tsx
- app/routes/_welcome+/onboarding.tsx
- app/routes/api+/stripe-webhook.ts
- app/utils/stripe.server.ts
Currently when a user wants free trial, we just give it via the stripe dashboard. 
However because we don't have hooks to manage free trials, we don't automatically update the DB, which can be a mess as it has to be managed manually now.
The goal of this PR is to automate this, so the sales team can give free subscriptions easily and not worry about cancelling them.
To do:
> improvement: webhook automation for free trial

- app/components/assets/custom-fields-inputs.tsx
- app/components/assets/form.tsx
- app/components/booking/form.tsx
- app/components/layout/header/absolute-positioned-header-actions.tsx
- app/components/list/pagination/per-page-items-select.tsx
- app/components/location/form.tsx
- app/components/shared/button-group.tsx
- app/components/shared/button.tsx
- app/routes/_layout+/assets.new.tsx
- app/routes/_layout+/locations.new.tsx
- app/routes/_layout+/settings.team.tsx
- app/styles/layout/button-group.css
- app/styles/layout/index.css
- Added save button in header and card on creating new asset
- Added save button in header when creating a new location
- Changed global size of buttons to sm from md
- Added add-another and cancel actions for location and asset form
- Created generic component for placing action buttons in header
- Created button-group component
- fixed breadcrumb of settings/team
- Changed size of per-page-select to make it consistent with new button sizes
> Save button & UI improvements

- app/components/dynamic-dropdown/dynamic-dropdown.tsx
- app/hooks/use-model-filters.ts
- app/modules/asset/service.server.ts
- app/routes/_layout+/assets._index.tsx
- app/utils/list.ts
Add location filter on assets index page to filter out assets based on given location.
Fix : #841
> feat(location-filter): add location filter on asset index page

- app/modules/organization/service.server.ts
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/settings.workspace.$workspaceId.edit.tsx
- docs/docker.md
- Made getOrganization only require id
- replaced the query for organization in ._edit to a inline query, scoped by the owner
- removed getOrganization on ._edit as we already have the current organization returned by requirePermission
> Fix organization bug on asset edit

- app/modules/auth/components/continue-with-email-form.tsx
- app/routes/_auth+/send-otp.tsx
- added client side validation so the proper zod message is shown when there is an invalid email
- Updated where and how server side errors are displayed
> improving error handling on otp email form

- app/modules/auth/service.server.ts
- app/modules/user/service.server.ts
- app/routes/_auth+/otp.tsx
- app/utils/extract-image-name-from-supabase-url.tsx
- app/utils/storage.server.ts
Fixing some errors from sentry.
> Fixing sentry errors

- app/components/admin/generate-batch-qr.tsx
- app/components/admin/mark-batch-as-printed.tsx
- app/components/layout/sidebar/organization-select-form.tsx
- app/components/layout/sidebar/organization-select.tsx
- app/components/layout/sidebar/sidebar.tsx
- app/components/list/filters/index.tsx
- app/components/list/pagination/per-page-items-select.tsx
- app/database/migrations/20240425131533_make_user_id_and_organization_id_not_required_for_qr_codes/migration.sql
- app/database/migrations/20240425172353_changes_related_to_unclaimed_codes/migration.sql
- app/database/migrations/20240426172829_add_print_batch_model/migration.sql
- app/database/schema.prisma
- app/modules/asset/service.server.ts
- app/modules/qr/service.server.ts
- app/routes/_layout+/admin-dashboard+/_layout.tsx
- app/routes/_layout+/admin-dashboard+/qrs.codes[.zip].ts
- app/routes/_layout+/admin-dashboard+/qrs.tsx
- app/routes/api+/$organizationId.qr-codes[.zip].ts
- app/routes/qr+/$qrId.tsx
- app/routes/qr+/$qrId_.contact-owner.tsx
- app/routes/qr+/$qrId_.link.tsx
- app/utils/list.ts
- app/utils/stripe.server.ts
- app/utils/zip-qr-codes.ts
- made it so userId and organizationId are not required for qr codes
- updated some services that needed change due to different fields
- created new services for generating unclaimed codes
- created admin dashboard index for qrs
- created endpoint to generate and print unclaimed codes
- created a util that takes an array of Prisma.Qr and generates a zipBlob with svgs of those codes
- changed batch from a field within Qr to its own model with Relation to Qr
- updated qr codes index for admin to have better data
- added filter based on batch name/id
- added a form that allows to mark a batch as printed
> Unclaimed codes

- app/modules/booking/constants.ts
- app/modules/booking/service.server.ts
- app/modules/booking/types.ts
- app/modules/booking/worker.server.ts
- app/utils/scheduler.server.ts
- merge booking related queues into 1 to reduce polling and refracted the code accordingly
- increase polling interval to 2 mins from 2 seconds.
- remove cron job support to avoid unnecessary polling(`noScheduling:true`).
- keep old queues for backward compatible reason
> fix: optimize scheduler to reduce DB queries

- app/components/assets/actions-dropdown.tsx
- app/components/assets/update-gps-coordinates-form.tsx
- app/components/workspace/nrm-actions-dropdown.tsx
- app/components/workspace/users-actions-dropdown.tsx
- app/routes/_layout+/assets.$assetId.duplicate.tsx
- app/utils/use-controlled-dropdown-menu.ts
implemented a custom hook to be used when having DropdownMenu which is controlled. This was needed because of the controlled dropdown menu not auto closing when clicking outside of it
> Fix: clicking outside controlled dropdown menu is not closing it

- app/components/subscription/current-plan-details.tsx
- app/components/subscription/prices.tsx
- app/routes/_layout+/settings.subscription.tsx
> refactor how prices are displayed on the subscription page

- app/components/list/index.tsx
- vite.config.ts
`List` component is being used `asChild` within the tabs, which creates an issue because of `SlotClone`. Changing the List component to `forwardRef` solves the issue as per recommended here: https://github.com/radix-ui/primitives/issues/1013
> fix: forwardRef on List component

- app/components/booking/availability-label.tsx
- app/routes/_layout+/bookings.$bookingId.add-kits.tsx
The "Already booked" label was showing for any kit that had bookings in the future, because the assets in the query were not scoped based on the current booking start and end date.
> fix: kit availability label

- app/components/subscription/successful-subscription-modal.tsx
- app/components/workspace/form.tsx
- app/emails/stripe/welcome-to-trial.tsx
- app/emails/styles.ts
- app/routes/_layout+/account-details.subscription.tsx
- app/routes/_layout+/account-details.workspace.new.tsx
- app/routes/api+/stripe-webhook.ts
- app/utils/stripe.server.ts
We have the issue that users get a team trial and continue working in their personal workspace. I have implemented a series of measures to help with that:
1. After user gets team trial or just directly buys team(without having a previous team workspace), they get redirected to `workspace/new`
2. They will be shown a modal informing them about the importance of creating a team workspace and giving some instructions.
3. If they are on the new workspace page and try to leave the page, I have implemented a blocker that asks them if they are sure
4. Once they get a free trial, they will also receive an email with instructions as requested in #1229
> feat: help users create their first Team workspace

- app/utils/custom-fields.ts
Issue with parsing field definition names in csv header was leading to a failure when importing multiline text. Has been resolved.
> fix: wrong parsing of field definition on import

- app/root.tsx
- app/routes/qr+/route.tsx
Root route exports were not updated to the latest Remix standard so it was creating an issue with unstyled errors when a certain layout doesnt have error boundary and the errors bubbled up to the root.
> fix: updating layout export in root

- app/utils/client-hints.tsx
- app/utils/custom-fields.ts
Used for cases where we just need to display a date, with time being irrelevant. 
Native JS always set back the date based on user timezone even if time is irrelevant for us. So we implemented this approach that uses `date-fns` and native `toLocaleDateString`.
Thanks to @rajeshj11 for investigating and helping understand the problem.
> feat: format date only based on locale

- app/components/dashboard/most-scanned-assets.tsx
- app/components/dashboard/most-scanned-categories.tsx
- app/components/dashboard/newest-assets.tsx
- app/components/list/bulk-actions/bulk-list-header.tsx
- app/components/list/bulk-actions/bulk-list-item-checkbox.tsx
- app/components/list/index.tsx
- app/components/table.tsx
- app/hooks/use-table-overflow.ts
- app/routes/_layout+/admin-dashboard+/qrs.tsx
- app/routes/_layout+/assets._index.tsx
- app/routes/_layout+/bookings.tsx
- app/routes/_layout+/categories.tsx
- app/routes/_layout+/kits.$kitId.tsx
- app/routes/_layout+/kits._index.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/locations._index.tsx
- app/routes/_layout+/settings.team.users.tsx
- app/routes/_layout+/tags.tsx
- app/styles/global.css
/closes #969 
showing the table and providing the horizontal scroll if any overflow is there.
Impact: mobile device will able to view the table data.
> feat:show table in mobile with hscroll

- app/components/assets/asset-custody-card.tsx
- app/components/assets/notes/note.tsx
- app/components/user/request-delete-user.tsx
- app/database/migrations/20240816120345_adding_cascading_deletes_for_user_and_organizations/migration.sql
- app/database/migrations/20240816121348_add_more_cascading_deletes_for_user/migration.sql
- app/database/migrations/20240816131518_updating_note_user_relationship/migration.sql
- app/database/migrations/20240820122636_add_deleted_at_to_user_for_soft_delete/migration.sql
- app/database/schema.prisma
- app/modules/user/service.server.ts
- app/routes/_layout+/account-details.general.tsx
- app/routes/_layout+/admin-dashboard+/$userId.tsx
To prevent database issues and data loss, we do soft delete.
To comply with regulations, we will destroy all personal data related to the user
To soft delete the user we do the following:
1. Update the user email to: `deleted+{randomId}@deleted.shelf.nu`
2. Update the user username to: `deleted+{randomId}`
3. Update the user `firstName` to: Deleted
4. Update the user `lastName` to: User
5. Delete the user's profile picture
6. Remove all relations to organizations the user is part of but doesnt own
7. Move all entities the user created inside organizations the user is part of but doesnt own to the owner of the organization
> feat: User soft delete

- app/components/assets/import-content.tsx
- app/modules/asset/service.server.ts
- app/modules/qr/service.server.ts
- public/static/shelf.nu-example-asset-import-from-content.csv
Resolves #1290 
This needs to be tested. It is deployed to staging. 
We have quite a few error scenarios. Here is what we are already handling in the code. Let me know if I missed an edge case as that could be.
Error cases to test 
1. Duplicate codes - multiple assets having the same code
2. Non existent codes - codes that don't exist in shelf
3. Linked codes - codes that are already linked to an asset or kit
4. Belonging to other org - codes that are part of other organizations
5. Empty - doing an import where `qrId` is added only for some of the assets being imported
6. No qrId column - when the `qrId` column is completely missing from the import file.
> feat: allow linking of QR codes on import

- app/components/booking/booking-assets-column.tsx
- app/components/list/list-item.tsx
- app/styles/global.css
Closes #1368
/claim #1368
https://github.com/user-attachments/assets/4f4e2754-5909-4f30-a217-c15eaf55d9f5
> Added dropdown in booking page assets management

- app/modules/asset/service.server.ts
- app/routes/_layout+/assets.$assetId.overview.add-to-existing-booking.tsx
- app/routes/_layout+/kits.$kitId.add-to-existing-booking.tsx
dont track ui error for not selecting a booking when adding asset to existing booking
> chore: remove unnessary error capturing on sentry

- app/components/assets/bulk-assign-custody-dialog.tsx
- app/components/kits/bulk-assign-custody-dialog.tsx
- app/modules/custody/schema.ts
- app/routes/_layout+/assets.$assetId.overview.assign-custody.tsx
- app/routes/_layout+/kits.$kitId.assign-custody.tsx
- create a helper that generates schema for validating custody json object
- implement the updated schema for bulk and singular custody assignment for kit and assets
- implement the updated schema for front-end validations on assign-custody routes for both kit and asset. Before there were only server side validations
> fix: assign custody validation schema

- app/modules/location/service.server.ts
Wrong usage of transaction was causing an error. Fixes #1415
> fix: wrong usage of transaction when bulk deleting locations

- app/components/assets/import-content.tsx
- app/modules/asset/service.server.ts
- app/modules/asset/types.ts
- app/routes/_layout+/assets.import.tsx
- public/static/shelf.nu-example-asset-import-from-content.csv
- allow for user to choose if an asset is bookable via import
- simply add a column called 'bookable' to your csv sheet and use 'yes' || 'no' as value
- update the example file to include this column
- handle cases where value is left empty or column is not added at all. Default value is true as with normal asset create
> improvement: handle 'availableToBook' on asset import

- app/components/assets/booking-actions-dropdown.tsx
- app/components/kits/booking-actions-dropdown.tsx
- made sure the book button doesn't render on assets and kits in personal organizations
- updated a broken if case that was doing the opposite of what it should for kit Book button
> fix: issues with book button rendering

- fly.toml
Bluegreen is creating an issue with DB timeouts. It creates new machines which consume connections to the pooler which are not accounted for. This strategy should prevent the issue or at least greatly minimize it.
> change deploy strategy

- package-lock.json
- package.json
- fixes a vulnaribility with `cross-spawn` that is a dependency of `npm-run-all`: https://github.com/mysticatea/npm-run-all/issues/264
> chore: bump cross-spawn

- app/components/assets/form.tsx
- app/components/kits/form.tsx
- app/components/location/form.tsx
- app/components/workspace/edit-form.tsx
- app/components/workspace/form.tsx
- app/routes/_layout+/account-details.general.tsx
- app/utils/constants.ts
this change prompts the user with their camera on mobile devices rather than file upload when creating or updates assets
adds the capture attribute to the input field see https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/capture for reference
> Mobile Camera Image Upload

- app/components/assets/assets-index/advanced-filters/value-field.tsx
- app/components/assets/assets-index/filters.tsx
- app/components/assets/bulk-assign-custody-dialog.tsx
- app/components/booking/form.tsx
- app/components/list/pagination/index.tsx
- app/modules/asset/data.server.ts
- app/modules/team-member/service.server.ts
- app/routes/_layout+/admin-dashboard+/org.$organizationId.assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/locations.$locationId.tsx
- app/routes/_layout+/settings.team.users.$userId.assets.tsx
- make sure to use `resolveTeamMemberName` in the booking for as name was not being displayed correctly
- create a helper type: `TeamMemberWithUserData`
- create a function that checks and updates corrupted team members: `fixTeamMembersNames`
- fixing a weird thing in getTeamMemberForCustodianFilter. It was doing some `combinedTeamMembers` where it was using the `userId` as the id in a `TeamMember[]`
- removed all uses or `rawTeamMembers` as we seem to not need it anymore
> fix: multiple issues with bookings and custodian selector

- app/components/assets/custom-fields-inputs.tsx
- app/components/assets/form.tsx
- completely dropped using Select from radix as it didnt work as we want
- implemented same UI as in the field selector on the asset index including search and arrow nav
- fixed some other UI stuff on the asset form
> improvement: updated OPTION custom field UI

- app/modules/booking/service.server.ts
- app/modules/invite/service.server.ts
- app/routes/_layout+/bookings.tsx
- made sure that for self service and base users we are also querying bookings with teamMemberId
- updated getBookings to support an OR query when both user and teamMember id are passed
- added a feature that when accepting an invite, if there are any bookings attached to the team member, we update them by linking them also to the user
> fix: base and self service users cannot see bookings

- app/routes/_layout+/settings.team.users.invite-user.tsx
- Make sure to block sending an invite if there are already pending invites the the same email and same workspace
- Display a clear error message to handle this case
> fix: dont allow multiple pending invites for the same org

- app/modules/asset/service.server.ts
- app/modules/team-member/service.server.ts
- app/modules/user/utils.server.ts
- app/routes/_auth+/otp.tsx
- app/routes/_layout+/account-details.general.tsx
- do not capture error for bulk assigning/releasing custody of assets if not all selected assets fit criteria
- create a function to generateUniqueUsername with attempts to make sure we dont have any uniqueConstraints. This was caused by an error in sentry for a automatically generated username on /otp route
- do not capture 'Email is already taken' error
- improved how we handle the function that fixes teamMember when they have no name
> fix: minor error handling issues

- app/components/assets/assets-index/advanced-filters/operator-selector.tsx
- app/modules/asset/data.server.ts
- app/modules/asset/utils.server.ts
- app/utils/cookies.server.ts
- app/utils/csv.server.ts
We have found a bug with the advanced index This shouldn't happen but it happened to some of our users, so we need a way to handle it to prevent an error if it happens again.
So lets say you navigate to this url: http://localhost:3000/assets?status=AVAILABLE
But you have advanced index mode active.
The params structure in the advanced index is different, however status is a proper param name. So it was crashing because it was trying to parse AVAILABLE as a advanced index filtering param but it doesnt have the correct format.
THe format in the url above is the one we use on simple index. I am not sure how this leaked to the url params in the case of our user. My only thought is that they already had advanced mode active and they typed in their url bar and this was the automatic URL …
> fix: wrong advanced filter formatting handling

- app/components/zxing-scanner/success-animation.tsx
- app/components/zxing-scanner/zxing-scanner.tsx
> fix(lottie-react): create component to render lottie on client only

- app/components/layout/sidebar/parent-nav-item.tsx
- app/database/migrations/20241218134155_add_indexes_for_better_asset_search_performance/migration.sql
- app/database/migrations/20241218134451_remove_asset_search_view/migration.sql
- app/database/schema.prisma
- app/modules/asset/fields.ts
- app/modules/asset/service.server.ts
- app/routes/_layout+/locations.$locationId.add-assets.tsx
We have been facing a lot of query errors and performance issues with the `AssetSearchView`. It was considerably slower than the normal search so I have taken the decision to drop it and replace it with prisma queries that create the same functionality. Based on my tests this is already way more performant than the view.
What has been done:
- removed function that searches in view for asset index
- updated getAssets to do the same as the search view but by using OR to search in all fields
- updated assetIndexFields to properly reflect the fields needed for the asset index
- removed AssetSearchView from schema
- created migration to remove AssetSearchView from DB
- created migration to add some more indexes to even better improve performance of simple asset index
- fixed a small bug with …
> fix: removed AssetSearchView

- app/database/migrations/20241230135956_test_mg/migration.sql
- app/database/post-migration.ts
- app/database/protected-indexes.ts
- app/database/schema.prisma
- app/routes/_welcome+/_layout.tsx
- docs/README.md
- docs/protected-indexes.md
- package.json
We created some indexes with a manual migration, so when we create a new migration they were getting automatically dropped as they are not reflected in schema.prisma.  This PR resolves this my adding those indexes to the schema so they dont get dropped every time.
- added all direct table indexes to schema. Those indexes were defined with a custom migration so we have to add them to the schema to prevent issues when generating new migrations
- fixed small issue with welcome layout
- implemented post-migration scripts that run after generating a new migration
- added a script protected-indexes which protects certain indexes from being dropped as they are not defined in `schema.prisma` due to prisma limitations - https://github.com/prisma/prisma/issues/12914
- created documentation about …
> fix: prisma schema mismatch with DB

- app/components/assets/import-content.tsx
- app/components/dashboard/inventory-value-chart.tsx
- app/components/dashboard/location-ratio-chart.tsx
- app/components/layout/sidebar/app-sidebar.tsx
- public/static/shelf.nu-example-asset-import-from-content.csv
- fix the safari bug for positioning of elements on dashboard
- update import docs to properly reflect date format
- fix bug in sidebar notice card being visible in collapsed sidebar
> fix: 1545-bug-safari-dashboard-ui-bug

- app/database/migrations/20250102153310_enable_row_level_security_for_asset_to_tag/migration.sql
I have been getting warnings saying row level security is not enabled for `_prisma_migrations` and `_AssetToTag`. I have added a migration to enable it for `_AssetToTag` however I was struggling with `_prisma_migrations` I think due to the table not existing in the "shadow database". I have manually enabled it and things seem to still work so maybe we could add it to the docs or I could play so more with getting a migration working.
> feat: adds row level security to _AssetToTag table

- app/components/assets/custom-fields-inputs.tsx
- app/utils/csv.server.ts
- app/utils/custom-fields.ts
> fix(asset-import): fix issue with boolean field while importing

- app/components/assets/assets-index/advanced-asset-index-filters-and-sorting.tsx
- app/components/assets/assets-index/advanced-filters/operator-selector.tsx
- app/components/assets/assets-index/advanced-filters/schema.ts
- app/modules/asset/query.server.ts
Allows to filter advanced index by excluding tags.
This PR also adds a small button that allows users to recommend more filtering options to be implemented.
> feature: add excludeAny for tags filters on advanced index

- app/components/booking/booking-assets-column.tsx
- app/components/booking/kit-row-actions-dropdown.tsx
- app/components/booking/remove-asset-from-booking.tsx
- app/components/dynamic-dropdown/dynamic-dropdown.tsx
- app/modules/booking/service.server.ts
- app/modules/booking/types.ts
- app/modules/types.ts
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.tsx
- app/routes/_layout+/calendar.tsx
- app/routes/_layout+/settings.team.invites.tsx
- app/routes/_layout+/settings.team.users.tsx
- app/utils/bookings.ts
**New**
- added custodian dropdown component to bookings index
- updated bookings index loader queries to load the required data for custodian filtering
- updated getBookings to receive array of custodianTeamMemberIds instead of just 1
- updated bookings index to pass the array of teamMemberIds to the getBookings function
**Fixes**
- fixed removed some types and helpers exports from bookings route file as it was breaking HMR
- fix types exported from wrong file, causing HMR failure
- fixed disabled state in search field inside DynamicDropdown
> feat: custodian filtering on bookings index

- app/components/assets/form.tsx
- app/routes/_layout+/assets.$assetId_.edit.tsx
- app/routes/_layout+/assets.new.tsx
> fix(cancel-button): update cancel button behavior on asset edit page

- app/components/booking/form.tsx
> feat(booking-date): update endDate when startDate is changed

- app/emails/mail.server.ts
- app/routes/_layout+/account-details.general.tsx
For better deliverability, based on feedback from Resend.
> chore: changing default email sender

- app/modules/asset/types.ts
- app/modules/asset/utils.server.ts
- app/routes/_layout+/admin-dashboard+/org.$organizationId.tsx
- app/routes/_layout+/assets.import.tsx
- app/utils/import.server.ts
> fix(import-header-error): add zod validation and showing proper error message for invalid data

- app/components/user/request-delete-user.tsx
- app/emails/email.worker.server.ts
- app/emails/mail.server.ts
- app/emails/types.ts
- app/entry.server.tsx
- app/modules/booking/constants.ts
- app/modules/booking/email-helpers.ts
- app/modules/booking/service.server.ts
- app/modules/booking/worker.server.ts
- app/modules/invite/service.server.ts
- app/modules/user/utils.server.ts
- app/routes/_layout+/account-details.general.tsx
- app/routes/_welcome+/onboarding.tsx
- app/routes/api+/stripe-webhook.ts
- app/utils/scheduler.server.ts
- ability to enqueue failed emails and retry them later
- **why not push all emails to queue**? because, then we need need to increase pg-boss polling frequency(more queries to postgress every minute), if not users will always have to wait for X minute to receive any email, some tokens/OTPs will have lifetime of X minutes 
- We dont await  `triggerEmail` call inside `sendEmail` anymore, so that any user facing actions can finish without waiting for email send to complete, this is actually a tradeoff, because if email sending fails(1st attempt + 5 retries using queues) user never will be warned, but the case is very unlikely and the benefit supersedes the tradeoff.
> add email queue to handle email sending failures

- app/modules/user/service.server.ts
We had a case that was not handled.
1. User exists as an sso user
2. User was not belonging to any org
3. User permissions get updated to belong to a new org via SCIM
4. User should be automatically updated on next login
> update: handled a case that was missing with SSO user transition

- .env.example
- app/components/subscription/price-cta.tsx
- app/components/welcome/choose-purpose.tsx
- app/config/shelf.config.ts
- app/config/types.ts
- app/routes/_welcome+/select-plan.tsx
- app/utils/env.ts
- app/utils/stripe.server.ts
- allow for free trial days to be set using an env variable
- add some explanation to the .env.example file
- update every reference of the free trial duration to use the env variable value
> update: change free trial control

- .env.example
- app/emails/transporter.server.ts
- app/utils/env.ts
- docs/docker.md
- docs/get-started.md
- test/setup-test-env.ts
Closes https://github.com/Shelf-nu/shelf.nu/issues/1681
This implementation should be fully backwards-compatible, since it falls back to the old default (port 465) if the env variable is not present.
> Add env variable for the SMTP port

- app/routes/api+/stripe-webhook.ts
- When a subscription is updated, only update the tier in shelf if the updates subscription has higher tier than the current shelf tier
- When a subscription is ended, only update the tier in shelf if the updated subscription has higher tier than the current shelf tier
- When a subscription is paused, only update the tier in shelf if the updated subscription has higher tier than the current shelf tier
> fix: handle subscription updates based on tier:

- app/components/forms/input.tsx
- app/components/scanner/drawer.tsx
- app/components/shared/icons-map.tsx
- app/components/zxing-scanner/code-scanner.tsx
- app/routes/_layout+/bookings.$bookingId.scan-assets.tsx
- vite.config.ts
> update: design of scanning UI for both camera and barcode scanner

- app/components/booking/form.tsx
There was an error reported by a user, that when adjusting the `endDate` in the new booking form, the whole page would crash. This issue happened only in safari. 
After some tinkering i found that that because we're using `endDate` as both the key and the value of this controlled input component. When a user types into the input field:
1. The `onChange` handler is triggered
2. `setEndDate` is called with the new value
3. The component re-renders with the new `endDate` value
4. Because `key={endDate}` changes, React completely unmounts and remounts the input component
This creates an infinite loop or state corruption that causes Safari to crash
Change the key of the `endDate` input field in the booking form
> Fix: adjust endDate input key to resolve the issue

- server/instrument.server.ts
Add `shelf_trace_id` to tags for better searching UX
> Improvement: error tracking with sentry

- app/modules/qr/service.server.ts
- app/routes/_layout+/admin-dashboard+/org.$organizationId.qr-codes.tsx
Small typo fix I noticed while using a selfhosted instance of shelf.
> Typo fix: unlinkned -> unlinked

- app/components/booking/create-booking-dialog.tsx
- on smaller screens the new booking modal was not fitting vertically so I added a max height
> fix: new booking modal overflow

- app/routes/qr+/route.tsx
- when scanning an asset and being redirected to the not-logged-in route, the link of the logo in the layout was broken
> fix: broken link

- app/atoms/atoms-reset-handler.tsx
- app/atoms/file.ts
- app/components/assets/form.tsx
- app/components/kits/form.tsx
- app/components/location/form.tsx
- app/components/workspace/edit-form.tsx
- app/components/workspace/form.tsx
- app/modules/asset/service.server.ts
- app/routes/_layout+/account-details.general.tsx
- app/routes/_layout+/account-details.workspace.$workspaceId.edit.tsx
- app/routes/_layout+/account-details.workspace.new.tsx
- app/routes/_layout+/locations.$locationId_.edit.tsx
- app/routes/_layout+/locations.new.tsx
- app/routes/_layout+/settings.general.tsx
- app/utils/constants.ts
- app/utils/storage.server.ts
- update atom that validates file upload size on the front-end to be dynamic, as we have different file sizes in different cases
- implement 2 atoms based on the new validation way - one for default and one for asset images
- update constants to manage max image size
- add server side validations for asset image file uploading
- make sure file validation atom is reset on route change
- create a new helper function that calculates Async Iterable file size
> fix: file upload size management

- docs/get-started.md
When we started with shelf we were still not sure how exactly we would handle storage and access to our images, so we implemented quite generic RLS policies for our storage. Those policies were designed in a way to leave space for us to implement client side(browser) requests for images, while still keeping them private enough.
Now that we are 2 years down the line we have come to the realization that we will not be doing any client side requests for images.
To address this we have updated the recommended RLS policies for storage to block all client side requests.
> Improvement: modifying docs for setting up policies

- app/components/user/sso-user-badge.tsx
- app/components/workspace/edit-form.tsx
- app/routes/_layout+/account-details.workspace.$workspaceId.edit.tsx
- app/routes/_layout+/admin-dashboard+/$userId.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.members.tsx
- app/routes/_layout+/admin-dashboard+/org.$organizationId.tsx
- app/routes/_layout+/settings.general.tsx
- app/routes/_layout+/settings.team.users.tsx
- show a table in the user admin view, that visualizes the count of users with sso enabled for all workspaces owned by said user
- in admin dashboard organization members page, show a label with SSO if a user is sso
- some other small ui updates
- Only allow OWNER to edit organization SSO settings. Closes #1825
> improvement: detailed sso user count info in admin dashboard

- app/modules/booking/service.server.ts
- app/routes/_layout+/bookings.$bookingId.add-assets.tsx
- app/routes/_layout+/bookings.$bookingId.add-kits.tsx
- if the booking was ongoing or overdue, the status of the asset was not synced
- when creating notes for adding assets, we were creating them for all assets in the booking, not just the ones we added, so if an asset was already in the booking it would still get a new note it was added. This was resolved for kits as well
> fix: issues with adding asset to bookings 

- app/components/assets/assets-index/assets-availability.tsx
- app/components/assets/assets-index/use-asset-availability-data.ts
- app/components/assets/assets-index/use-calendar-now-indicator-fix.ts
- package-lock.json
- package.json
There is an issue with the `resourceTimeline` of full calendar which has been known since 2022 but has still not been fixed, I can imagine due to complexity. What happens is that when the default view of the resource timeline is anything different than `resourceTimelineDay` the now indicator doesn't get placed on the correct place. 
Here is a link to the full research: https://claude.ai/public/artifacts/18c76b8a-19af-46fd-a596-e37e8c9f8264
So I created a  Custom hook to fix the FullCalendar now indicator issue by switching views and ensuring the calendar is ready for interaction. This hook switches the view to the target view (`resourceTimelineMonth`) when the calendar is ready and ensures the now indicator is visible. This means that default view has to be set to `resourceTimelineDay` so …
> fix: calendar nowIndicator

- app/components/assets/assets-index/create-booking-for-selected-assets-dialog.tsx
- app/components/booking/buffer/buffer-settings.tsx
- app/components/booking/forms/edit-booking-form.tsx
- app/components/booking/forms/fields/tag-field.tsx
- app/components/booking/forms/forms-schema.ts
- app/components/booking/forms/new-booking-form.tsx
- app/components/booking/tags-required/tags-required-settings.tsx
- app/components/multi-select/multi-select.tsx
- app/components/tag/tags-autocomplete.tsx
- app/components/working-hours/toggle-working-hours-form.tsx
- app/database/migrations/20250717094237_add_tags_required_flag_to_booking_settings/migration.sql
- app/database/schema.prisma
- app/modules/asset/data.server.ts
- app/modules/booking-settings/service.server.ts
- app/modules/working-hours/zod-utils.ts
- app/routes/_layout+/admin-dashboard+/$userId.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/routes/_layout+/bookings.new.tsx
- app/routes/_layout+/settings.bookings.tsx
- add a flag in BookingSettings to control whether tags are required
- create a form in settings.booking to toggle the tagsRequired flag
- update action and schema in settings.booking to support the new toggle
- update BookingFormSchema to receive tagsRequired and handle it accordingly
- update all booking forms to receive the new props and properly render the tags field with the required option handled
- update asset index loaders to load not only tags for asset filters but also tags for bookings form
- update MultiSelect component to receive a 'required' prop
- update TagsAutocomplete to receive an error and required props
> feat: optional required tags for bookings

- app/components/booking/actions-dropdown.tsx
- app/modules/booking/service.server.ts
- app/routes/_layout+/bookings.$bookingId.duplicate.tsx
- app/utils/stripe.server.ts
> feat(duplicate-booking): create feature to duplicate booking

- app/modules/asset/service.server.ts
- app/utils/storage.server.ts
- When image `sizeCalculation` fails, it was returning null which is invalid value for the cache so it was breaking. WE set the default size to 0 if it returns null
- if image download fails when importing, skip the image and don't throw an error just continue the process
> Fix: bug with lru cache on import

- prisma.config.ts
Add dotenv/config import to prisma.config.ts to ensure environment variables are loaded when using the new Prisma configuration format. This resolves the 'Environment variable not found: DIRECT_URL' error that occurred after migrating from package.json to prisma.config.ts.
> Fix: Prisma config to load environment variables

- app/components/shared/date.tsx
- app/components/working-hours/overrides/override-preview.tsx
- app/components/working-hours/working-hours-preview-dialog.tsx
Working hours overrides were displaying incorrect dates due to timezone conversion during formatting. Users selecting "August 29th" would see "August 28th" displayed in certain timezones (e.g., US Eastern).
Changes made:
- Add localeOnly prop to DateS component for timezone-neutral formatting
- Create formatAbsoluteDate utility function using date-fns
- Parse date strings manually to avoid timezone interpretation
- Apply localeOnly formatting to working hours override components
- Preserve all Intl.DateTimeFormatOptions (weekday, month, etc.) in absolute formatting
Technical approach:
- Extract date-only part from datetime strings (2025-08-29T00:00:00.000Z → 2025-08-29)
- Parse as local date components: new Date(year, month-1, day)
- Use date-fns format() with converted format strings to …
> Fix: working hours override date display timezone issue

- app/routes/_layout+/kits.$kitId.tsx
The custody field was being selected in both `GET_KIT_STATIC_INCLUDES` and `extraInclude`, causing redundancy. Removed the extra custody select since `GET_KIT_STATIC_INCLUDES` already provides all necessary custody fields including `createdAt`.
Moreover this resolves #2024 as the extra include was not selecting `createdAt` so that was causing a bug.
> refactor: remove redundant custody extraInclude in kit loader

- app/components/booking/booking-assets-column.tsx
- app/modules/booking/utils.server.ts
- app/routes/_layout+/bookings.$bookingId.checkin-assets.tsx
- app/routes/_layout+/bookings.$bookingId.tsx
- app/utils/booking-assets.ts
The booking progress bar was showing incorrect values (e.g., 160/482 instead of 482/482) for completed bookings because the system wasn't properly handling final booking statuses.
Changes made:
- Update calculatePartialCheckinProgress to return 100% progress for COMPLETE/ARCHIVED bookings
- Pass booking status to progress calculation in booking loaders
- Show check-in audit columns for COMPLETE/ARCHIVED bookings to maintain audit trail
- Add helpful tooltips to check-in column headers
- Update asset partial check-in logic to include final statuses
This ensures users see accurate progress (482/482 = 100%) and retain visibility into who checked in assets and when, even after booking completion.
Fixes issue where users couldn't see completion progress or audit information for bookings that …
> Fix partial check-in progress display for COMPLETE and ARCHIVED bookings

- app/components/assets/asset-status-badge.tsx
- app/components/assets/assets-index/advanced-asset-columns.tsx
- app/components/booking/availability-label.tsx
- app/modules/booking/service.server.test.ts
- app/modules/booking/service.server.ts
- test/components/booking/availability-label.test.tsx
When an asset was checked in for one booking and checked out in another (both ongoing), the status badge incorrectly showed the booking where the asset was already checked in instead of the one where it was still checked out.
Root cause: The backend query didn't filter out bookings where assets had been partially checked in, and the frontend had complex logic trying to use a bookings prop that lacked partial check-in context.
Changes:
- Backend: Added partialCheckins filter to getOngoingBookingForAsset to exclude bookings where the asset has been partially checked in
- Frontend: Simplified AssetStatusBadge to always use the API call for CHECKED_OUT status, removed unused bookings prop
- Components: Updated all AssetStatusBadge usages to remove the bookings prop
- Availability Label: Fixed …
> Fix: asset status badge showing wrong booking when asset is partially checked in
